name: Security

on:
  push:
    branches:
      - master
      - '*-maint'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
      - '*-maint'

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # via Zizmor example
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0 # v5.0.0
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
