name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          - os: windows-2019
            python-version: pypy3
            # TODO: Remove this; see:
            #       https://github.com/actions/setup-python/issues/151
            #       https://github.com/tox-dev/tox/issues/1704
            #       https://foss.heptapod.net/pypy/pypy/-/issues/3331
    env:
      BABEL_CLDR_NO_DOWNLOAD_PROGRESS: "1"
      BABEL_CLDR_QUIET: "1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install tox tox-gh-actions==2.1.0
    - name: Run test via Tox
      run: tox --skip-missing-interpreters
    - uses: codecov/codecov-action@v1
